---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - imdi-servicemesh.intel.com
  resources:
  - imdioperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - imdi-servicemesh.intel.com
  resources:
  - imdioperators/finalizers
  verbs:
  - update
- apiGroups:
  - imdi-servicemesh.intel.com
  resources:
  - imdioperators/status
  verbs:
  - get
  - patch
  - update
