apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-manager-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-cert
  namespace: istio-system # should be in the same namespace as istio-ingressgateway
spec:
  commonName: 'CRYPTOMB GW'
  dnsNames:
  - '*.intel.com'
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-issuer
  secretName: istio-gateway-secret
