---
# Source: mychart/templates/istiooperator.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  tag: "1.18.0-intel.0-rc.1"
  hub: "ccr-registry.caas.intel.com/intel-istio/istio"
  meshConfig:
  # Enable for envoy debugging
  # accessLogFile: /dev/stdout
    defaultConfig:
      proxyStatsMatcher:
        inclusionPrefixes:
          - "listener"
      # Allows cryptomb bucket statistics via EnvoyFilter 
      proxyMetadata:
        BOOTSTRAP_XDS_AGENT: "true"
  components:
    egressGateways:
    - name: istio-egressgateway
      enabled: true
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      namespace: istio-system
      k8s:
        overlays:
        - kind: Deployment
          name: istio-ingressgateway
          patches:
          - path: spec.template.spec.containers.[name:istio-proxy].args.[-1]
            value: --concurrency=4
          - path: spec.template.spec.containers.[name:istio-proxy].securityContext.capabilities.add
            value: [ "IPC_LOCK" ]
        resources:
          requests:
            cpu: 4000m
            memory: 4096Mi
            qat.intel.com/cy: "1"
            qat.intel.com/dc: "1"
          limits:
            cpu: 4000m
            memory: 4096Mi
            qat.intel.com/cy: "1"
            qat.intel.com/dc: "1"
        hpaSpec:
          maxReplicas: 1
          minReplicas: 1
        podAnnotations:
          proxy.istio.io/config: |
            privateKeyProvider:
              qat:
                pollDelay: 5ms
