//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CryptoMBSetSpec) DeepCopyInto(out *CryptoMBSetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CryptoMBSetSpec.
func (in *CryptoMBSetSpec) DeepCopy() *CryptoMBSetSpec {
	if in == nil {
		return nil
	}
	out := new(CryptoMBSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePluginSetSpec) DeepCopyInto(out *DevicePluginSetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePluginSetSpec.
func (in *DevicePluginSetSpec) DeepCopy() *DevicePluginSetSpec {
	if in == nil {
		return nil
	}
	out := new(DevicePluginSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImdiOperator) DeepCopyInto(out *ImdiOperator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImdiOperator.
func (in *ImdiOperator) DeepCopy() *ImdiOperator {
	if in == nil {
		return nil
	}
	out := new(ImdiOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImdiOperator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImdiOperatorList) DeepCopyInto(out *ImdiOperatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ImdiOperator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImdiOperatorList.
func (in *ImdiOperatorList) DeepCopy() *ImdiOperatorList {
	if in == nil {
		return nil
	}
	out := new(ImdiOperatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImdiOperatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImdiOperatorSpec) DeepCopyInto(out *ImdiOperatorSpec) {
	*out = *in
	if in.DevicePlugin != nil {
		in, out := &in.DevicePlugin, &out.DevicePlugin
		*out = new(DevicePluginSetSpec)
		**out = **in
	}
	if in.IngressGateways != nil {
		in, out := &in.IngressGateways, &out.IngressGateways
		*out = make([]*IngressGatewaySpec, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(IngressGatewaySpec)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	out.SetupProxy = in.SetupProxy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImdiOperatorSpec.
func (in *ImdiOperatorSpec) DeepCopy() *ImdiOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(ImdiOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImdiOperatorStatus) DeepCopyInto(out *ImdiOperatorStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImdiOperatorStatus.
func (in *ImdiOperatorStatus) DeepCopy() *ImdiOperatorStatus {
	if in == nil {
		return nil
	}
	out := new(ImdiOperatorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressGatewaySpec) DeepCopyInto(out *IngressGatewaySpec) {
	*out = *in
	if in.Qat != nil {
		in, out := &in.Qat, &out.Qat
		*out = new(QatSetSpec)
		**out = **in
	}
	if in.CryptoMB != nil {
		in, out := &in.CryptoMB, &out.CryptoMB
		*out = new(CryptoMBSetSpec)
		**out = **in
	}
	if in.Sgx != nil {
		in, out := &in.Sgx, &out.Sgx
		*out = new(SgxSetSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressGatewaySpec.
func (in *IngressGatewaySpec) DeepCopy() *IngressGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(IngressGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxySetSpec) DeepCopyInto(out *ProxySetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxySetSpec.
func (in *ProxySetSpec) DeepCopy() *ProxySetSpec {
	if in == nil {
		return nil
	}
	out := new(ProxySetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QatSetSpec) DeepCopyInto(out *QatSetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QatSetSpec.
func (in *QatSetSpec) DeepCopy() *QatSetSpec {
	if in == nil {
		return nil
	}
	out := new(QatSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SgxSetSpec) DeepCopyInto(out *SgxSetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SgxSetSpec.
func (in *SgxSetSpec) DeepCopy() *SgxSetSpec {
	if in == nil {
		return nil
	}
	out := new(SgxSetSpec)
	in.DeepCopyInto(out)
	return out
}
